Adding access patterns doc
ustaxcourt/ef-cms pull request #1015
Opened 2021-04-06 14:02 UTC by codyseibert

adding an access pattern document and .csv file so that people can get a better high level overview of the PK/SK/GS1PKs we use for our various data models.

2021-04-06 14:40 UTC, matthopson commented on docs/ACCESS_PATTERNS.md
> +| associate a irs practitioner onto a case                   | case\|${CASE_ID}                                | irsPractitioner\|${USER_ID}              |
"an" irs practitioner

2021-04-06 14:41 UTC, matthopson commented on docs/ACCESS_PATTERNS.md
> +| add a case not to the user                                 | user-case-note\|${USER}                         | user\|${USER_ID}                         |
"note"

2021-04-06 14:43 UTC, matthopson approved these changes
Couple small typos (I didn't note them in the csv, but they're there too)

2021-04-06 15:02 UTC, mmarcotte commented on docs/ACCESS_PATTERNS.md
> +| docket number generator counter                            | docketNumberCounter-2021                        | docketNumberCounter-${YEAR}              |
I guess the PK would also be:
```
docketNumberCounter-${YEAR}   
```

2021-04-06 15:04 UTC, mmarcotte commented on docs/ACCESS_PATTERNS.md
> +| associate practitioner by bar number for lookup            | privatePractitioner\|${BAR_NUMBER}              | user\|${userId}                          |
Love the list. I just wonder if you could sort by PK. I think everything falls into order better for my 🧠

2021-04-06 19:48 UTC, mmarcotte requested changes
just wondering if you could address the above, thanks Cody!

2021-04-07 13:39 UTC, mmarcotte approved these changes

2021-04-07 13:40 UTC, merged