Bug 7946: File Upload element for "Supporting Document" is not consistent with other file inputs
ustaxcourt/ef-cms pull request #1283
Opened 2021-06-01 15:43 UTC by rachelschneiderman

Before:
![image](https://user-images.githubusercontent.com/20249233/120352225-90017c00-c2ce-11eb-95bf-0163ad243da0.png)

After:
![image](https://user-images.githubusercontent.com/20249233/120352020-5f214700-c2ce-11eb-881b-175f8b4e1587.png)

2021-06-01 19:28 UTC, mmarcotte requested changes

2021-06-01 19:28 UTC, mmarcotte commented on web-client/src/views/FileDocument/StateDrivenFileInput.jsx
> +    file: props.file,
Have a look at the linting catch below. `file` is already defined. We might want to break out that function or use a more descriptive name here for `file`.

2021-06-02 15:45 UTC, kkoskelin approved these changes
Once `no-shadow` rules are in the clear, you betcha.

2021-06-02 15:57 UTC, mmarcotte approved these changes

2021-06-02 19:25 UTC, merged