9595: Visibility Across Consolidated Case Group
ustaxcourt/ef-cms pull request #3155
Opened 2023-02-22 14:53 UTC by TomElliottFlexion

2023-02-22 19:16 UTC, zRogersFlexion approved these changes

2023-02-23 17:09 UTC, mmarcotte requested changes
Looks great! One pretty straightforward test fix from me.

2023-02-23 17:09 UTC, mmarcotte commented on shared/src/business/entities/cases/Case.isUserPartOfGroup.test.js
> +  });
I think this is meant to have `{ userId: 'abc' }` be in the `irsPractitioners` array

2023-02-23 17:55 UTC, mmarcotte approved these changes
thanks!

2023-02-23 18:57 UTC, jimlerza approved these changes

2023-02-23 20:38 UTC, merged