Devex 1148 Move policy.json to shared/terraform/bin
ustaxcourt/ef-cms pull request #3332
Opened 2023-03-23 22:11 UTC by rosiehsmith

https://trello.com/c/TFbEKZET/1148-move-policyjson-to-shared-terraform-bin

2023-03-24 15:38 UTC, rachelschneiderman approved these changes

2023-03-24 19:27 UTC, jimlerza requested changes
I think you will also need to change the path to `policy.json` on [line 42 of `shared/terraform/bin/create-bucket.sh`](https://github.com/flexion/ef-cms/blob/devex-1148-policy-json/shared/terraform/bin/create-bucket.sh#L42)

See [line 7 of `shared/terraform/bin/init.sh`](https://github.com/flexion/ef-cms/blob/devex-1148-policy-json/shared/terraform/bin/init.sh#L7) for an example of how to determine the path to `shared/terraform/bin` when you don't know the current working directory (and it might be different, as is the case when running terraform).

2023-03-24 19:47 UTC, jimlerza approved these changes

2023-03-28 16:39 UTC, mmarcotte approved these changes

2023-03-28 16:39 UTC, merged