Like Console.log()... but Pink!
ustaxcourt/ef-cms pull request #3351
Opened 2023-03-27 22:42 UTC by zRogersFlexion

Small utility function to use in debugging that prints to any console in pink and puts json Object in a pretty format. Has the exact same signature as console.log();

![Pasted Graphic](https://user-images.githubusercontent.com/81588260/228082957-3b4a32d2-3a2f-46b3-a42a-b5037c80b277.png)

2023-03-28 00:34 UTC, jasonfu9966 requested changes

2023-03-28 00:34 UTC, jasonfu9966 commented on shared/src/tools/pinkLog.ts
> +  const pink: string = '\x1b[35m';
but this is magenta.
please review.

2023-03-30 14:03 UTC, codyseibert commented
seems useful when trying to find stuff in the long output logs of our system.  I may even say we could have this pinkLog imported in our applicationContext and have it decorate console with console.pink if we are running locally.  This would prevent us from needing to manually import pinkLog in every file we want to debug with it.

2023-04-03 13:42 UTC, shumway-tm approved these changes

2023-04-03 13:43 UTC, shumway-tm commented
The days of camouflaged console logs in our api log are finally numbered!

2023-04-03 14:51 UTC, jasonfu9966 approved these changes

2023-04-06 18:37 UTC, mmarcotte approved these changes

2023-04-06 18:37 UTC, merged