DevEx: Fix IRS superuser script and add documentation for how to use it
ustaxcourt/ef-cms pull request #3473
Opened 2023-04-20 18:44 UTC by jimlerza

2023-04-20 19:47 UTC, mmarcotte approved these changes
love it!

2023-04-20 19:51 UTC, jasonfu9966 approved these changes
I have tested this and it works

2023-04-20 20:06 UTC, zRogersFlexion requested changes
Looks good to me just need the imports and exports to be es6

2023-04-20 20:06 UTC, zRogersFlexion commented on scripts/irs-super-user.ts
> +const { requireEnvVars } = require('../shared/admin-tools/util');
Nice switch over to Typescript! Can you make all of the imports/exports es6?

2023-05-03 14:55 UTC, zRogersFlexion approved these changes

2023-05-03 14:58 UTC, merged