Resolve race condition undrafting
ustaxcourt/ef-cms pull request #3707
Opened 2023-06-29 20:43 UTC by mmarcotte

2023-07-05 14:43 UTC, zRogersFlexion requested changes
If this is a brand new file could we make it in typescript and use aws-sdk v3 rather than v2?

e.g. import { DynamoDB } from '@aws-sdk/client-dynamodb';

If this is a one time script that will be thrown away I am okay with it being Javascript, but could we make a folder to express that?

2023-07-06 14:16 UTC, jimlerza commented
> If this is a one time script that will be thrown away, could we make a folder to express that?

I created [devex-1197](https://trello.com/c/qcNDhaXf) for organizing our admin scripts, perhaps we could utilize the directory structure proposed in that card.

2023-08-14 20:56 UTC, mmarcotte commented
@zRogersFlexion -- thanks for the feedback! I've added a test, switched to TS, and used v3 api.

2023-08-15 19:12 UTC, zRogersFlexion approved these changes

2023-08-15 20:52 UTC, merged