OpEx: find cases involving practitioners who work for a specific law firm
ustaxcourt/ef-cms pull request #4163
Opened 2023-11-01 19:00 UTC by jimlerza

Today we had a request from docket to deliver a list of all cases involving private practitioners employed by a specific law firm. We expect to field more requests like this in the future.

2023-11-01 21:24 UTC, jtdevos requested changes

2023-11-01 21:24 UTC, jtdevos commented on shared/admin-tools/elasticsearch/find-firms-cases.ts
> +              },
Could these be parameterized w/ command-line arguments?

2023-11-02 13:50 UTC, TomElliottFlexion approved these changes

2023-11-02 15:02 UTC, jtdevos approved these changes

2023-11-02 15:52 UTC, merged