1137 devex
ustaxcourt/ef-cms pull request #4317
Opened 2023-11-27 19:12 UTC by Absolutestunna

[Devex Card](https://trello.com/c/bHHK51Jg/1137-reconsider-rehome-stateaddeddocketnumbers)

1. Remove the dependencies on `state.addedDocketNumbers`.
2. Removed actions setting `state.addedDocketNumbers`.
3. Compute selected cases using `state.modal.form.consolidatedCasesToMultiDocketOn`.

2023-12-11 18:14 UTC, zRogersFlexion requested changes
Only blocking for the updates to the cypress tests.

2023-12-11 18:14 UTC, zachrog commented on cypress/cypress-integration/integration/docket-clerk-multi-docket-draft-order.cy.ts
> +  it('should edit the draft order with newly selected cases', () => {
Nice addition of the cypress test. LOVE IT.

To try and follow some of the best practices we have for cypress I think we would want all of these steps inside of a single it block, or each it block needs to have setup that allows it to run independently from one another.

Over from our 'integration-tests.md':
every it statement should be a repeatable test that should be able to run in isolation. This means your it statement shouldn't depend on a previous it statement to pass. If you write tests that depend on previous it statements, your tests can become flaky. This also goes against the best practices outlined in the cypress docs.

2023-12-11 18:14 UTC, zachrog commented on shared/src/business/utilities/getSelectedConsolidatedCasesToMultiDocketOn.ts
> +): string[] | [] => {
I think this can just be string[]

2023-12-11 18:14 UTC, zachrog commented on web-client/src/presenter/actions/CourtIssuedOrder/getPdfFromUrlAction.ts
> +}> => {
🍾

2023-12-11 18:14 UTC, zachrog commented on web-client/src/presenter/actions/setRedirectUrlAction.ts
> +  redirectUrl: string;
🍾

2023-12-11 18:14 UTC, zachrog commented on web-client/src/presenter/actions/setSelectedConsolidatedCasesToMultiDocketOnAction.test.ts
I am not quite sure I understand what this piece of state is doing. What is tate.setSelectedConsolidatedCasesToMultiDocketOn being used for?

2023-12-11 18:14 UTC, zachrog commented on web-client/src/presenter/sequences/gotoEditOrderSequence.ts
> +export const gotoEditOrderSequence = sequence<{
I think you are looking for the new style of typing sequences. 

[] as unknown as ({docketEntryIdToEdit, docketNumber}: {docketEntryIdToEdit: string, docketNumber: string}) => void

2023-12-11 22:22 UTC, Absolutestunna commented on web-client/src/presenter/sequences/gotoEditOrderSequence.ts
> +export const gotoEditOrderSequence = sequence<{
Good catch. Made the adjustment in this commit: 
eb07f92

2023-12-11 22:23 UTC, Absolutestunna commented on cypress/cypress-integration/integration/docket-clerk-multi-docket-draft-order.cy.ts
> +  it('should edit the draft order with newly selected cases', () => {
I understand. I moved the setup (login) and variable declarations into their respective `it` blocks. Commit: 
eb07f92

2023-12-11 22:29 UTC, Absolutestunna commented on web-client/src/presenter/actions/setSelectedConsolidatedCasesToMultiDocketOnAction.test.ts
`setSelectedConsolidatedCasesToMultiDocketOn` is being used in `addDocketNumbersModalHelper` and `createOrderHelper` to determine the correct verbiage and icons to render when selecting the cases to file an order on. 

The derived state `state.addedDocketNumbers` was previously used to compute the verbiage and icons.

2023-12-12 16:19 UTC, zRogersFlexion approved these changes

2023-12-13 17:59 UTC, mmarcotte approved these changes

2023-12-13 18:00 UTC, merged