10249 fix pre epoch cases intermediate branch to test 1710967520
ustaxcourt/ef-cms pull request #4770
Opened 2024-03-20 20:45 UTC by mmarcotte

This PR allows cases with a `receivedAt` of before the UNIX date time epoch to show up in the Custom Case Report as well as the downloadable custom case report. For the first page of the Custom Case Report, we will simply not include a `searchAfter` parameter to the Opensearch query instead of the default `receivedAt` of `0`. This way `receivedAt` with negative values will be included.

<img width="1501" alt="Screenshot 2024-03-20 at 4 41 49 PM" src="https://github.com/ustaxcourt/ef-cms/assets/5023502/1ee4e350-a48e-417d-a3d0-8a8c5598c685">

2024-03-20 20:49 UTC, jimlerza approved these changes

2024-03-20 20:51 UTC, rachelschneiderman requested changes
Is there a cypress test that could be written that would have caught this? Maybe paper file a case so you can set the received at date to something pre-1970?

2024-03-29 20:43 UTC, mmarcotte commented
> Is there a cypress test that could be written that would have caught this? Maybe paper file a case so you can set the received at date to something pre-1970?

Sure thing. I added some logic to `cypress/cypress-integration/integration/custom-case-report-csv-export.cy.ts` test.

2024-03-29 20:44 UTC, rachelschneiderman approved these changes

2024-04-30 15:13 UTC, merged