10534 design debt
ustaxcourt/ef-cms pull request #5544
Opened 2024-11-13 20:17 UTC by btejha

2024-11-20 18:23 UTC, jimlerza requested changes

2024-11-20 18:23 UTC, jimlerza commented on package-lock.json
I don't think we want changes to this file in this PR.

2024-11-20 18:23 UTC, jimlerza commented on tmp.md
Please remove this file as well.

2024-11-20 20:58 UTC, btejha commented on tmp.md
oops forgot to removed it, done.

2024-11-20 20:59 UTC, btejha commented on package-lock.json
Understood.

2024-11-20 21:26 UTC, pixiwyn approved these changes

2024-11-22 20:01 UTC, jimlerza approved these changes

2024-11-22 20:02 UTC, merged