Dependency updates December 5
ustaxcourt/ef-cms pull request #5632
Opened 2024-12-05 18:00 UTC by JayFlexy

Dependency updates, new docker image required.

2024-12-06 14:35 UTC, jimlerza approved these changes

2024-12-06 14:50 UTC, TomElliottFlexion commented on scripts/verify-terraform-version.sh
>    echo "Please set your terraform version to 1.9.8 before deploying."
```suggestion
  echo "Please set your terraform version to 1.10.1 before deploying."
```

2024-12-06 14:50 UTC, TomElliottFlexion commented on scripts/verify-terraform-version.sh
>    echo "Please set your terraform version to 1.9.8 before deploying."
Tiny nit

2024-12-06 15:01 UTC, TomElliottFlexion requested changes
Did this end up getting a migration?

2024-12-06 18:22 UTC, JayFlexy commented
> Did this end up getting a migration?

Ah, good catch! Doing now

2024-12-11 11:09 UTC, pixiwyn requested changes
This isn't building, possible issues with tf/aws provider updates, been debugging this, please hold on merging this till resolved.

2024-12-11 13:41 UTC, pixiwyn commented
This update cannot go as is. Posted message about moving onto next week's dependency updates in USTC Project chat. Closing this PR.

2024-12-11 13:41 UTC, closed without merging